# Generated by Django 3.2.4 on 2021-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Участник'), (1, 'Автор')], default=0, verbose_name='Тип'),
        ),
    ]
