version: "3.8"

services:
  web:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - src/.env
    environment:
      - SECRET_KEY={SECRET_KEY}
      - DEBUG={DEBUG}
      - MAILGUN_API_KEY={MAILGUN_API_KEY}
      - MAILGUN_SENDER_DOMAIN={MAILGUN_SENDER_DOMAIN}

  redis:
    image: redis:6.2.4-alpine

  celery:
    build: .
    command: celery -A core worker -l INFO
    depends_on:
      - web
      - redis
    env_file:
      - src/.env
    environment:
      - SECRET_KEY={SECRET_KEY}
      - DEBUG={DEBUG}
      - MAILGUN_API_KEY={MAILGUN_API_KEY}
      - MAILGUN_SENDER_DOMAIN={MAILGUN_SENDER_DOMAIN}

