# Generated by Django 3.2.5 on 2021-07-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_request_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set(),
        ),
    ]
