# Generated by Django 3.2.5 on 2021-07-02 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_alter_request_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('event', 'user')},
        ),
    ]
